# GUIDANCE FOR ADDING A PLUGIN TABLE
# REQUIRED KEYS
# `[plugin-name]`
#   - The table key should be the plugin's name minus the `avogadro-` prefix.
#
# - `git` or `src`
#   - Indicate how to obtain the plugin's source code.
#   - A repository on GitHub only needs to provide `git.repo` and `git.commit`.
#   - Git repositories in locations other than GitHub are not currently
#     supported, but please tell us if you'd have liked to have had the option!
#   - An archive at some URL should instead provide `src.url` and `src.sha256`
#     - The format of the archive must be one of: zip, tar, gztar, bztar, or
#       xztar.
#     - `sha256` is the SHA-256 hash of the downloaded archive, not the
#       decompressed files.
#
# REQUIRED KEYS IF NOT DEFAULT
# These keys have default values if they are not specified.
# - `path`
#   - Used to indicate where the plugin's source code is to be found within the
#     repository/archive.
#   - Use `/` as the path separator, not `\`
#   - If this is specified, you probably want to specify `readme-url` too.
#   - default = "."
#
# - `metadata`
#   - The plugin's metadata file, located at `path`.
#   - options = ["pyproject.toml", "avogadro.toml"]
#   - default = "pyproject.toml"
#
# - `plugin-type`
#   - options = ["pypkg", "pyscript"]
#   - default = "pypkg"
#
# OPTIONAL KEYS
# - `release-tag`
#   - If the plugin is in a GitHub repository and the given commit corresponds
#     to a specific release, you should provide the tag of the release.
# - `readme-url`
#   - A URL that Avogadro can use to get the README file for display in the
#     Avogadro GUI.
#   - If not specified, if the plugin is in a GitHub repository, the README of
#     the repo will be used; thus, if `path` is specified, you probably want to
#     specify this too.

# [demo-pypkg]
# git.repo = "https://github.com/matterhorn103/avo-plugin-demo.git"
# git.commit = "819acef635f2a146970499d6d37a743d77ebd4fe"
# path = "avogadro-demo-pypkg"

[generators]
git.repo = "https://github.com/OpenChemistry/avogenerators.git"
git.commit = "12a58630dde5b7184dfafd97e67e0022c49f7a09"

[rdkit]
git.repo = "https://github.com/ghutchis/avogadro-rdkit.git"
git.commit = "5954c943d40484881cf0a97486150cbe115cc2d8"

[cclib]
git.repo = "https://github.com/OpenChemistry/avogadro-cclib.git"
git.commit = "91110cf4714eda8e3e258413553d48a5690cddd5"

[build-ase]
git.repo = "https://github.com/ghutchis/avogadro-build-ase.git"
git.commit = "2c3c72f2b97fc0231c2628a221c3dc519166c422"

[xtb]
git.repo = "https://github.com/matterhorn103/avo_xtb.git"
git.commit = "2e9289d462bc8fb8bf79ba02a7435f4013ec7945"
release-tag = "0.11.0"

[xtb-energy]
git.repo = "https://github.com/ghutchis/avogadro-xtb-energy.git"
git.commit = "287e8093f65bca5b9d27fbf517a8719ae319d108"

[aimnet2]
git.repo = "https://github.com/ghutchis/avogadro-aimnet2.git"
git.commit = "3c9cce218a681d6ad07389b197919c9d6799b5a6"

[genice]
git.repo = "https://github.com/ghutchis/avogadro-genice.git"
git.commit = "c511d64a07aa3260fb5a297847020c668819fcef"

[turtlemol]
git.repo = "https://github.com/ghutchis/avogadro-turtlemol.git"
git.commit = "eb1b4ab77ec7a4130209445e8c6736d170286998"

[multicharge]
git.repo = "https://github.com/ghutchis/avogadro-multicharge.git"
git.commit = "bbc0d7bd093a87b1e27227ea861847e3485a9d3a"

[antechamber-charges]
git.repo = "https://github.com/ghutchis/avogadro-antechamber-charges.git"
git.commit = "5f6c70b459d8f76ebc08545cf1107d6b3ec384e3"

[chiraltube]
git.repo = "https://github.com/ghutchis/avogadro-chiraltube.git"
git.commit = "170467fc57c4363587bc5dfb206d5c36ad61039f"

[mace]
git.repo = "https://github.com/ghutchis/avogadro-mace.git"
git.commit = "a408a390d88c97d2d05b744786d3e6f45c0668cc"

[pymatgen]
git.repo = "https://github.com/ghutchis/avogadro-pymatgen.git"
git.commit = "aa1fb4c448ec112e3a75b171325fc1ff79b912ef"

[mdtraj]
git.repo = "https://github.com/ghutchis/avogadro-mdtraj.git"
git.commit = "62ee266e340b6dcb10a6f6d8468c7532ab98653f"

[ob-energy]
git.repo = "https://github.com/ghutchis/avogadro-ob-energy.git"
git.commit = "812474ae62749bc99f76b747f7a80d0afe774bfe"

[mattersim]
git.repo = "https://github.com/ghutchis/avogadro-mattersim.git"
git.commit = "525a745aa33c580e70e2ad2e7b94874bfde0eca8"

[ani-energy]
git.repo = "https://github.com/ghutchis/avogadro-ani-energy.git"
git.commit = "9a752e1e9044e4eac0504baf7f414697440aa4f2"

[psi4-cubeprop]
git.repo = "https://github.com/ghutchis/avogadro-psi4-cubeprop.git"
git.commit = "d1cd86cf9dd5154fe3066a64d5e500dc9ac9fe8e"

[crest]
git.repo = "https://github.com/matterhorn103/avogadro-crest"
git.commit = "4ac0a3135fc62e6e5c3d04a56a6b828a0050936e"
release-tag = "0.1.1"
