# The table key should be the plugin name minus the `avogadro-` prefix!

[demo-pypkg]
git.repo = "https://github.com/matterhorn103/avo-plugin-demo.git"
git.commit = "819acef635f2a146970499d6d37a743d77ebd4fe"
path = "avogadro-demo-pypkg"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[generators]
git.repo = "https://github.com/OpenChemistry/avogenerators.git"
git.commit = "5226d49bba54a42e6479a10876f7d3d317f9ff6d"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[rdkit]
git.repo = "https://github.com/ghutchis/avogadro-rdkit.git"
git.commit = "f6dd12fb64f0c2fed05ed5391ce264651713c7aa"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[cclib]
git.repo = "https://github.com/OpenChemistry/avogadro-cclib.git"
git.commit = "69927f5a7ed158bafe333305bd5c5fe4afb6134c"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[build-ase]
git.repo = "https://github.com/ghutchis/avogadro-build-ase.git"
git.commit = "b54b0cbecf3fdc5f1a2de834615776a33f7d85ec"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[xtb-energy]
git.repo = "https://github.com/ghutchis/avogadro-xtb-energy.git"
git.commit = "ddd6d87dadc144307e51cbab69857e86a52aec7c"
metadata = "pyproject.toml"
plugin-type = "pypixi"

[aimnet2]
git.repo = "https://github.com/ghutchis/avogadro-aimnet2.git"
git.commit = "3c6542ff8e0c81be6e634a7a622c7a4f8097137d"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[genice]
git.repo = "https://github.com/ghutchis/avogadro-genice.git"
git.commit = "206eb2b670d666d603e340a9bf06f8a2d634efae"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[turtlemol]
git.repo = "https://github.com/ghutchis/avogadro-turtlemol.git"
git.commit = "eb1b4ab77ec7a4130209445e8c6736d170286998"
metadata = "pyproject.toml"
plugin-type = "pypkg"

[multicharge]
git.repo = "https://github.com/ghutchis/avogadro-multicharge.git"
git.commit = "bbc0d7bd093a87b1e27227ea861847e3485a9d3a"
metadata = "pyproject.toml"
plugin-type = "pypixi"

[antechamber-charges]
git.repo = "https://github.com/ghutchis/avogadro-antechamber-charges.git"
git.commit = "5f6c70b459d8f76ebc08545cf1107d6b3ec384e3"
metadata = "pyproject.toml"
plugin-type = "pypixi"